spring:
    application:
        name: zoey-2024
    datasource:
        jdbcUrl: ENC(hmRYeWg6bn+edjQj43YBRNcqTIC3ribO/tsygOVNjJnoDGpMu+D0A+vDKphwkSdGivEnibStmbfo1ikVbR5t4oI9kYkNP9E9qTTpmKy4GmY=)
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: ENC(RWOOjBHrOxZIhadrxrVlt4FnON4/GkNk)
        password: ENC(yI9ehsRxakpx+C/R+0y6vA==)
        platform: postgres

jasypt:
  encryptor:
    bean: jasyptStringEncryptor

logging:
    level:
        jdbc:
            audit: OFF
            resultset: OFF
            resultsettable: OFF
            sqlonly: DEBUG
            sqltiming: OFF

