spring:
    application:
        name: zoey-2024
    datasource:
        jdbcUrl: jdbc:log4jdbc:postgresql://localhost:5432/postgres?currentSchema=public
        driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        username: postgres
        password:
        platform: postgres


logging:
    level:
        jdbc:
            audit: OFF
            resultset: OFF
            resultsettable: OFF
            sqlonly: DEBUG
            sqltiming: OFF

